### ISSUE TITLE
Gramatyka, interpunkcja

### ISSUE THREAD

**Issue by Venominside** [goodideagiver/how-to-ask-good-questions#10]
**Describe the bug**

W oknie "co powinno się dziać vc co się dzieje" przecinek przed "ale" i zdanie nie brzmi logicznie. Powinno być "(...)do schowka, ale ten jest pusty."

**Screenshots**

![obraz](https://user-images.githubusercontent.com/49470841/193519699-9bdc75dd-b4e8-4e89-a952-bbe209fe731f.png)

**Comment by goodideagiver** [comment]
#15
